# build Vite
FROM node:20-alpine AS build-frontend
WORKDIR /app/frontend
COPY ./frontend/package*.json ./
RUN npm ci --no-audit --no-fund
COPY ./frontend .
RUN npm run build

# nginx runtime
FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-frontend /app/frontend/dist /usr/share/nginx/html
RUN mkdir -p /app/storage /app/api/public
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]